-
  name: 'Prep VMs for app deployment'
  hosts: virtual_machines
  become: yes
  tasks:
    -
      name: Disable swap
      command: swapoff -a
    -
      name: 'Install Docker'
      apt:
        name: docker.io
        state: latest
    -
      name: 'Install Docker service'
      service:
        name: docker
        enabled: yes
        state: started
#    -
#      name: 'Enable Docker'
#      command: usermod -aG docker $USER
#      command: newgrp docker
    -
      name: 'App key for k8s'
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    -
      name: 'Getting Kubernetes apt repo'
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
    -
      name: 'Install Kubernetes'
      
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

